### ISSUE TITLE
Recursive operations seem to get stuck

### ISSUE THREAD

**Issue by RoyCurtis** [bdew/compacter#1]
It seems when "Recursive compacting" is enabled and the Compacter compacts enough material into another material that can be further compacted, it does not do so until there is a block update. The update has to be in an adjacent block, or a state change in the Compacter.
## Reproduction
1. In a creative flatland world, [place a Compacter with a Creative Energy Cell on top](http://i.imgur.com/fD9EX9a.png)
2. Set the Compacter's redstone mode to "Disabled"
3. [Insert 4 stacks of Iron Nuggets](http://i.imgur.com/rMHKuXQ.png)
4. Change redstone mode to "Always ON"
5. Observe the outcome,
   - Expected: 4 nuggets, 1 ingot in input; 3 blocks in output
   - Actual: 4 nuggets, 28 ingots in input
6. Place a block against any side of the Compacter
7. Open the Compacter, observe that the 28 ingots have now been compacted to 3 iron blocks
## Testing environment
- Forge 1.7.10 10.13.3.1428
- [Compacter](http://minecraft.curseforge.com/mc-mods/231549-compacter/files/2242600) 0.1.0.4 & [BDLib](http://minecraft.curseforge.com/mc-mods/70496-bdlib/files/2242176) 1.8.2.92
- [AutoPackager](http://minecraft.curseforge.com/mc-mods/221457-autopackager/files/2241455) 1.5.4
- [WAILA](http://minecraft.curseforge.com/mc-mods/73488-waila/files/2230518) 1.5.10
- Thermal Suite:
  - [CoFH Core](http://curse.com/mc-mods/minecraft/cofhcore/2234198) 3.0.2-262
  - [Thermal Foundation](http://curse.com/mc-mods/minecraft/222880-thermal-foundation/2233780) 1.0.0-81
  - [Thermal Expansion](http://curse.com/mc-mods/minecraft/thermalexpansion/2234200) 4.0.1-182
  - [Thermal Dynamics](http://curse.com/mc-mods/minecraft/227443-thermal-dynamics/2233787) 1.0.0-122

**Comment by bdew** [comment]
Should be fixed in 0.1.1

**Comment by RoyCurtis** [comment]
Can confirm; thank you! Nice work
