### ISSUE TITLE
Deletion bug

### ISSUE THREAD

**Issue by Sunekaer** [bdew/compacter#10]
Middle clicking the compactors out inventory to sort, delete the items 

[Sorter](https://minecraft.curseforge.com/projects/inventory-sorter?gameCategorySlug=mc-mods&projectID=240633)

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.

**Comment by DatenThielt** [comment]
This still exists in 1.19.2
