### ISSUE TITLE
Won't accept certain item

### ISSUE THREAD

**Issue by calvissuperman** [bdew/compacter#11]
I'm not sure where this bug stems from, but the compacters in my Project Ozone 2 modpack is no longer accepting Sheep Essence (which has only one use, to 3x3 compact into 4 wool). I can't manually place the item in it, nor can I pipe them into it. This is after I had already successfully been compacting this essence and created over 20,000 wool with the compacter, it just decided to stop.

I was hoping to find something in the config file for accepted items, or maybe some script, but nothing has led me to find anything for this problem. If there is a solution like that, I am more than willing to edit files and such to fix it.

**Comment by calvissuperman** [comment]
And now after playing and shutting down the game at least 3 or so times it just started working again.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
