### ISSUE TITLE
Compacter stops with single recipe mode

### ISSUE THREAD

**Issue by bcdsant** [bdew/compacter#12]
When compacter is single recipe and the inventory is full they stop working, issue happen when turning iron blocks into iron ingots. After removing some stacks of iron blocks the compacter works, looks like an internal inventory problem.

**Comment by bdew** [comment]
The mod has been recently updated to MC 1.16, older versions are no longer supported.
I'm mass closing older issues to clear up clutter in the bug tracker.

If you find this issue still exists in the current version feel free to reopen it.
