### ISSUE TITLE
Internal server error / Disconnect from server

### ISSUE THREAD

**Issue by Dominance** [bdew/compacter#4]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/128

**Comment by bdew** [comment]
Seems to be a bug in enviromine - https://github.com/EnviroMine/EnviroMine-1.7/issues/165 - it passes the wrong coordinates to the block being clicked.

I'll add a workaround in BDLib that will make it fail more gracefully in all my mods, but if the wrong coordinates end up pointing to a different tile entity it will still crash - i don't see a way to prevent that.

**Comment by bdew** [comment]
Workaround in - https://github.com/bdew/bdlib/commit/2d539e8013c4763c1dbad5b2d102254c18899d2e
