### ISSUE TITLE
Enchancement Compacter specific recipe support

### ISSUE THREAD

**Issue by Dominance** [bdew/compacter#5]
Compacter specific recipe support. Current in Divergence there is a pressure packager block that works in tandem with a windmill. I would like to use compacter to replicate this as a more advanced version. It just fits so well and gives the compacter that much more purpose. Figured since I was here tossing a bug Id put this in a little better context than what twitter allows.

**Comment by CplPibald** [comment]
Can you give some more details on this?  At a minimum, would need the block's name and what mod it comes from. Even better, a description (or link to a wiki page) that tells exactly how it works.

**Comment by Dominance** [comment]
http://reasonable-realism.wikia.com/wiki/Pressure_Packager A rf version. Admittedly like I said it might of only be used in this method by a limited number of packs.

**Comment by CplPibald** [comment]
So you're asking for the custom recipes that the Pressure Packager adds, like snowblock->iceblock or sapling->compost?

It's not clear from that page if the mod is adding crafting recipes for these, or if they require a Pressure Packager to work.  Check if you can do the items 2x2 or 3x3 in a crafting table.  If you can, they will work in the Compacter.

Note that if you just need this for your modpack, you can add a recipe to the Compacter just by using a mod like MineTweaker to add a shaped recipe to the game, and the Compacter will detect it.

**Comment by Dominance** [comment]
As stated I would like it to be compacter specific recipes. I am well aware that it will pick up on any recipes added by what ever means you choose.  From the wiki page I linked. 

"The primary purpose of this block was to **compact** the ore chunks provided by Harder Ores into a block that Rotary Craft's Extractor could process in the expected manner."  

Some of the recipes added can only be done via the pressure packager. And while it works perfectly it also only operates on early game windmill type power. I am just looking for a faster more advanced so to say version that accomplishes the same thing. Helps scale with your technology level and progression. This is why it may only be used by this one pac and not by everything. To give something meaning and used by every player in the pack somewhere down the line. Compacter just seems like the most obvious choice to acomplish this. I could very well add in recipes to a railcraft rock crusher or a shapeless recipe if need be. I just wanted the immersive feel and for it to make sense.

**Comment by bdew** [comment]
We have discussed this on twitter before an i think i understand what's required. I'll add it soon(tm)

**Comment by bdew** [comment]
See https://github.com/bdew/compacter/blob/master/config_examples/custom.cfg

**Comment by bdew** [comment]
Also added support for the new modes (1x1 and hollow 3x3) by @CplPibald
